[package]
name = "asset_registry"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
bitcoin_hashes = { version = "0.3", features = [ "serde" ] }
failure = "0.1.5"
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4.5"
stderrlog = "0.4.1"
secp256k1 = "0.12.2"

[dependencies.rocket_contrib]
version = "0.4.0"
default-features = false
features = ["json"]
