[package]
name = "asset_registry"
version = "0.1.0"
authors = ["Nadav Ivgi <nadav@shesek.info>"]
edition = "2018"

[features]
default = [ "cli", "client" ]
dev = []
client = []
server = [ "rocket", "rocket_contrib" ]
cli = [ "structopt" ]

[dependencies]
rocket = { version = "0.4.0", optional = true }
bitcoin = { git = "https://github.com/shesek/rust-bitcoin", rev = "edge" , features = [ "serde" ] }
elements = { git = "https://github.com/shesek/rust-elements", rev = "edge", features = [ "serde" ]  }
bitcoin_hashes = { git = "https://github.com/stevenroose/bitcoin_hashes", rev = "bd75e6cfc90efd2c9e3999adf0d92e1a41866cbe", features = [ "serde" ] }
failure = "0.1.5"
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
log = "0.4.5"
stderrlog = "0.4.1"
secp256k1 = "0.12.2"
base64 = "0.10.1"
base64-serde = "0.3.2"
reqwest = "0.9.15"
lazy_static = "1.3.0"
idna = "0.1.5"
regex = "1.1.6"
structopt = { version = "0.2.15", optional = true }

[dependencies.rocket_contrib]
version = "0.4.0"
optional = true
default-features = false
features = ["json"]

[[bin]]
name = "server"
required-features = [ "cli", "server" ]

[[bin]]
name = "liquid-asset-registry"
required-features = [ "cli" ]
